"""
Student information for this assignment:

On my/our honor, Cesar Monagas Romero, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: cam9225
"""

from abc import ABC, abstractmethod
import random

DAILY_EXPENSE = 60
HAPPINESS_THRESHOLD = 50
MANAGER_BONUS = 1000
TEMP_EMPLOYEE_PERFORMANCE_THRESHOLD = 50
PERM_EMPLOYEE_PERFORMANCE_THRESHOLD = 25
RELATIONSHIP_THRESHOLD = 10
INITIAL_PERFORMANCE = 75
INITIAL_HAPPINESS = 50
PERCENTAGE_MAX = 100
PERCENTAGE_MIN = 0
SALARY_ERROR_MESSAGE = "Salary must be non-negative."


class Employee(ABC):
    """
    Abstract base class representing a generic employee in the system.
    """

    def __init__(self, name, manager, salary, savings):
        self.relationships = {}
        self.savings = savings
        self.is_employed = True
        self.__name = name
        self.__manager = manager
        self.__perf_score = INITIAL_PERFORMANCE
        self.__mood_level = INITIAL_HAPPINESS
        self.__wage = salary

    @property
    def name(self):
        return self.__name

    @property
    def manager(self):
        return self.__manager

    @property
    def performance(self):
        return self.__perf_score

    @performance.setter
    def performance(self, value):
        if value < PERCENTAGE_MIN:
            self.__perf_score = PERCENTAGE_MIN
        elif value > PERCENTAGE_MAX:
            self.__perf_score = PERCENTAGE_MAX
        else:
            self.__perf_score = value

    @property
    def happiness(self):
        return self.__mood_level

    @happiness.setter
    def happiness(self, value):
        if value < PERCENTAGE_MIN:
            self.__mood_level = PERCENTAGE_MIN
        elif value > PERCENTAGE_MAX:
            self.__mood_level = PERCENTAGE_MAX
        else:
            self.__mood_level = value

    @property
    def salary(self):
        return self.__wage

    @salary.setter
    def salary(self, value):
        if value < 0:
            raise ValueError(SALARY_ERROR_MESSAGE)
        self.__wage = value

    @abstractmethod
    def work(self):
        pass

    def interact(self, other):
        if other.name not in self.relationships:
            self.relationships[other.name] = 0

        if self.relationships[other.name] >= RELATIONSHIP_THRESHOLD:
            self.relationships[other.name] += 1
            self.happiness += 1

        elif self.happiness >= 50 and other.happiness >= 50:
            self.relationships[other.name] += 1

        else:
            self.relationships[other.name] -= 1
            self.happiness -= 1

    def daily_expense(self):
        self.happiness -= 1
        self.savings -= DAILY_EXPENSE

    def __str__(self):
        return (
            f"{self.name}\n"
            f"\tSalary: ${self.salary}\n"
            f"\tSavings: ${self.savings}\n"
            f"\tHappiness: {self.happiness}%\n"
            f"\tPerformance: {self.performance}%"
            )     


class Manager(Employee):
    """
    A subclass of Employee representing a manager.
    """
    def __init__(self, name, manager, salary, savings):
        super().__init__(name, manager, salary, savings)

    def work(self):
        """Simulates 1 hour of work for the manager."""
        perf_change = random.randint(-5, 5)
        self.performance += perf_change

        if perf_change <= 0:
            self.happiness -= 1
            for emp in self.relationships:
                self.relationships[emp] -= 1
        else:
            self.happiness += 1


class TemporaryEmployee(Employee):
    """
    A subclass of Employee representing a temporary employee.
    """
    def work(self):
        perf_change = random.randint(-15, 15)
        self.performance += perf_change
        if perf_change <= 0:
            self.happiness -= 2
        elif perf_change > 0:
            self.happiness += 1

    def interact(self, other):
        super().interact(other)
        if other == self.manager:
            if other.happiness > HAPPINESS_THRESHOLD and self.performance >= \
                TEMP_EMPLOYEE_PERFORMANCE_THRESHOLD:
                self.savings += MANAGER_BONUS
            elif other.happiness <= HAPPINESS_THRESHOLD:
                self.salary //= 2
                self.happiness -= 5
                if self.salary == 0:
                    self.is_employed = False


class PermanentEmployee(Employee):
    """
    A subclass of Employee representing a permanent employee.
    """
    def work(self):
        perf_change = random.randint(-10, 10)
        self.performance += perf_change
        if perf_change >= 0:
            self.happiness += 1

    def interact(self, other):
        super().interact(other)
        if other == self.manager:
            if other.happiness > HAPPINESS_THRESHOLD and self.performance >= \
                PERM_EMPLOYEE_PERFORMANCE_THRESHOLD:
                self.savings += MANAGER_BONUS
            elif other.happiness <= HAPPINESS_THRESHOLD:
                self.happiness -= 1
